### ISSUE TITLE
Can not re-subscribe after stream failure

### ISSUE THREAD

**Issue by mkhahani** [lynckia/licode#616] opened 2016-11-19 14:56 UTC
Trying to handle `stream-failed` event by re-subscribing to the same stream passed by the event with no luck. The SDP is sent but no response from the server is received and there is no error on the server side.

It's while the same approach works well for publisher, that is when a publish stream fails I can re-publish by handling `stream-failed` event.

PS: I use NetLimiter in order to drop or limit a connection(stream).

**Comment by simonemazzoni** [comment] 2017-02-08 17:36
I have the very same  problem.
I noticed that in case of `stream-failed` the property `failed` of the stream is set to 'true'

That value is then checked on signaling messages received, both from the server and other peers (not p2p and p2p), not processing the signaling message in case the stream has the `failed` property set to `true`.

Here the two part of `Room.js` where all happen.
 ```
// if !p2p
that.socket.on('signaling_message_erizo', function (arg) {
    var stream;
    if (arg.peerId) {
        stream = that.remoteStreams[arg.peerId];
    } else {
        stream = that.localStreams[arg.streamId];
    }

    if (stream && !stream.failed) {
        stream.pc.processSignalingMessage(arg.mess);
    }
});

// if p2p "You can see that the message is processed anyway"
that.socket.on('signaling_message_peer', function (arg) {

    var stream = that.localStreams[arg.streamId];

    if (stream && !stream.failed) {
        stream.pc[arg.peerSocket].processSignalingMessage(arg.msg);
    } else {
        stream = that.remoteStreams[arg.streamId];

        if (!stream.pc) {
            createRemotePc(stream, arg.peerSocket);
        }
        stream.pc.processSignalingMessage(arg.msg);
    }
});
```

The first workaround I find is to manually delete the `failed` property from the stream on `stream-failed`. This bypass that check and allow a stream to be published again.

The problem is that the `stream-failed` event could be fired both for a publisher and for a subscriber.
In the Subscriber `stream-failed` case I don't think it is correct or useful to allow a user to re-subscribe the same failed stream (since isn't on the server anymore).

In the Publisher `stream-failed` case I think instead that allow the user to republish his local stream is the correct thing to do.

I created a pull request with a possible fix. You can check it [here](https://github.com/lynckia/licode/pull/744)

Let me know.

Simone

**Comment by aalonsog** [comment] 2017-02-10 11:57
Republishing a stream that has previously failed is a very sensitive issue. There are several checks implied in both client and server side. So we have to handle it carefully. My opinion is that we would have to analyze every possible scenario and try to search a robust solution. 

Right now the client API is though to avoid the publication of a failed stream, so the solution is to create a new stream and publish it instead of the first one.

However, I still see an issue in the current implementation. To improve the behavior, the check should be done when publishing the stream, not when processing signaling messages from erizo. Thus, when you try to publish a stream with `stream.failed = true`, the API responds with an error message explaining that you have to create a new stream and publish it. 

What do you think? Could you propose a PR implementing this?

**Comment by simonemazzoni** [comment] 2017-02-10 13:03
Hello @aalonsog,

> Right now the client API is though to avoid the publication of a failed stream, so the solution is to create a new stream and publish it instead of the first one.

You mean make a new getUserMedia()? It isn't a waste of time and resources? Event if a stream fails remotely, its local version is still valid. Am I wrong?

As far as I know, if a stream is marked as `local` it means that is a stream owned by the user that receive the message. Furthermore, I noticed that the `stream-failed` routine it unpublish the stream from licode, it resets its peerconnection, it sets the `failed` property to `true` and then it fires the `stream-failed`. So the handling process is very similar to a normal unpublish with the difference that is originated by something else going wrong (e.g. ICE CANDIDATE NEGOTIATION FAIL or similar).
This led me to implement the pull request I just posted, because in the end the state of the room after a `stream-failed` is the same of after a stream unpublish.

> However, I still see an issue in the current implementation. To improve the behavior, the check should be done when publishing the stream, not when processing signaling messages from erizo. Thus, when you try to publish a stream with stream.failed = true, the API responds with an error message explaining that you have to create a new stream and publish it.

Also this is true. This is the reason why I had to check erizoJS code to understand whats happening.
I think I can implement the check you said, but then I have to review my client side code to handle a `stream-failed` by recreating a new local stream which, in my opinion, is not necessary.

What do you think?

Simone

**Comment by aalonsog** [comment] 2017-02-13 10:06
Hi @simonemazzoni, 

I agree with you, perhaps creating again the stream (and having to ask to user to accept media access) is not the best solution. 

You are also right that setting the `failed` property to the stream is followed by unpublishing it. Taking this into account I think the best solution is to set `failed` property to false again when the stream has been successfully unpublished (when the unpublish callback is called). Assuming that when the stream has been unpublished it is in the same status as initially and it is ready to be published again. I prefer this because we avoid possible future checks of `failed` property.

**Comment by simonemazzoni** [comment] 2017-02-13 10:09
Good, LGTM!

I'll make some tests with this logic and I'll make a new PR.

**Comment by aalonsog** [comment] 2017-02-13 10:09
Of course, this is complementary with avoiding to publish a stream that has `stream.failed = true`

**Comment by simonemazzoni** [comment] 2017-02-13 10:10
Yes, of course! I'll also implement the `stream.failed` check on publish to avoid the publish of failed streams.

**Comment by simonemazzoni** [comment] 2017-02-15 08:55
Hi @aalonsog, I implemented the solution we discussed here, but I noticed few things on the client side logic that I would like to discuss with you.

I noticed that, from publisher point of view, when a `stream-failed` event is raised, is then followed by a `stream-removed` one, because the stream-failed routine it unpublish the stream that has failed.
This looks good to me, because if the stream doesn't work anymore, is right to remove it from licode and to signal it to the subscribers.

Assuming this, the thing I don't understand, is the needs to send a 'stream-failed' event!
Wouldn't be easier and cleaner to send only the `stream-removed` event, eventually setting the `stream.failed` property to true?

I'm saying this because from a publisher point of view, it causes confusion, because if he receives a `stream-failed` event on a published stream, he can't republish the same stream until he received the associate `stream-removed` event from that stream. So what's the point of listening the `stream-failed`event? (This is the case of a stream-failed of a successfully published stream)

Furthermore, I noticed that in case of `stream-failed` during the publish routine, it's never fired the `stream-added` event to subscribers, but then is fired a `stream-removed`, so subscribers receive `stream-removed` events of streams never added.

I guess there is something mishandled in the logic.
Could you confirm that?

Please, tell me if I wasn't clear enough. It isn't an easy case to explain :)

**Comment by mkhahani** [comment] 2017-02-15 09:29
Let me clear the subject. There are two possible scenarios:
1. When the stream between **publisher** and the server fails.
2. When the stream between **subscriber** and the server fails.

In the first scenario it's obvious that the publisher needs to publish again, either by re-getting the user media or by re-publishing the same stream (if available).

The second scenario, which is more common and happens frequently for clients with poor Internet connection, of course it is the responsibility of the server to drop the failed stream and re-send it for the subscriber because the source stream from the publisher is still alive.

**Comment by simonemazzoni** [comment] 2017-02-15 09:50
@mkhahani I agree, for the first scenario.

> The second scenario, which is more common and happens frequently for clients with poor Internet connection, of course it is the responsibility of the server to drop the failed stream and re-send it for the subscriber because the source stream from the publisher is still alive.

For the second scenario I think that the only thing that the server can do is to signal the subscriber that the stream has failed, so that the subscriber can retry a new subscribe since the stream of the publisher is still alive.

**Comment by simonemazzoni** [comment] 2017-02-17 09:40
@aalonsog I updated my [PR](https://github.com/lynckia/licode/pull/744) . 

I implemented the error callback on both `publish` and `subscribe` if the stream has the `failed` property.

I also implemented the deletion of the `stream.failed` property on successful `unpublish` callback, to allow a user to try to republish its local stream as we discussed.

**Closed** 2018-01-25 04:20 UTC
