### ISSUE TITLE
Video freezes after several minutes in conference with simulcast (Chrome72+)

### ISSUE THREAD

**Issue by vpoddubchak** [lynckia/licode#1415] opened 2019-05-24 08:54 UTC
**Description**

After Chrome has been updated to v72, we started seeing problems with quality of video on receiving side when simulcast is ON. Sometimes (maybe linked to some bw fluctuations or loss), receiving video freezes and then never back.
From another side, publisher is still sending good quality video and another receiver can receive it fine. It means - problem is between subscriber and licode.

**Steps to reproduce the issue:**
1. Start conference with simulcast ON with 3 participants: A, B, C
2. Wait 2-3 min

**Describe the results you received:**
Participant A see: from B - good, **from C - freezes**
Participant B see: from A - good, **from C - good**
Participant C see: from A - good, from B - good

Users A and B see different quality of stream from C. For user B it freezes.

**Describe the results you expected:**
Good quality of video for all participants.

**Additional information you deem important (e.g. issue happens only occasionally):**
It started happening after Chrome v72. As I know they changed BWE mechanism.
Looked by Ackuaria to stream from Licode to subscriber. And there I can see that Estimated bandwidth drops to very low value and then sending bitrate drop also:
![image (3)](https://user-images.githubusercontent.com/6253301/58315144-988a6680-7e19-11e9-9daf-792af6c52111.png)

**Comment by lodoyun** [comment] 2019-06-04 22:49
After some testing we concluded the fallback mechanism (sending the last keyframe every 5 seconds) we implemented for simulcast has stopped working the way we wanted in newer Chrome versions. 
Since now it's possible to customize the bitrate for simulcast layers in Chrome, a solution is to get the lower layer to have lower bitrate and avoid using the fallback altogether.
Check out #1417.

**Comment by vpoddubchak** [comment] 2019-06-10 10:40
Thanks for update but it does not work for me.
I set _{simulcast: {numSpatialLayers: 3, spatialLayerBitrates: {0: 30000, 1: 120000, 3: 450000}}}_
But it still has problem: video freezes after 3 minutes in the meeting.

**Comment by lodoyun** [comment] 2019-06-10 11:29
Can you please post an ackuaria screenshot like last time?
In no case should the video freeze since we disabled that functionality with #1417

**Comment by vpoddubchak** [comment] 2019-06-11 07:35
I made simple test: enter to the room with Simulcast ON by 3 participants, 1 by 1.
Here are screenshots:
After 2nd participant entered the room, estimated bandwidth dropped from 280kbps to 120kbps:
![image (4)](https://user-images.githubusercontent.com/6253301/59252185-2d6fcb00-8c34-11e9-9183-da4c3b4a131f.png)
After 3rd participant enter the room:
![image (5)](https://user-images.githubusercontent.com/6253301/59252214-3f516e00-8c34-11e9-94f6-509366214c73.png)
After ~ 1 min I reproduced freezed video on one of participant, his stats:
![image (6)](https://user-images.githubusercontent.com/6253301/59252266-67d96800-8c34-11e9-8285-b8beae667c05.png)

**Comment by lodoyun** [comment] 2019-06-11 10:22
Every time a subscriber joins you're getting important dips in both subscribers and publishers. Notice how on the second image the highest layers are not present. You can check if this is due to packet loss in ackuaria (publisher side) or in webrtc-internals. I'd say it's pretty normal if your computer is overtaxed or the connection to the server is not that great. Are you simulating bad network conditions? Are you running 

The third one is really strange behaviour, you're not getting any video traffic at all from the publisher. We haven't been able to reproduce this. Can you please post a screenshot of both the publisher side in ackuaria when this happens and the bwe for that publisher in chrome://webrtc-internals (make sure you select `Legacy` in the `Read Stats from` dropdown.

**Comment by vpoddubchak** [comment] 2019-06-12 07:52
I agree that I may have limited bandwidth from my PC to the licode server. 

About freeze video, I made such test:
1. Simulcast is ON with 2 layers: 30kpbs and 450kbps.
2. Entered to the room with 4 participants: 
   - 2 from Chrome 74 (64bit) Win 
   - 2 from Ubuntu Chrome 74 on Ubuntu.
3. After 2-3 minutes I got frozen one video on one client (the same video was OK for others.)

Screenshots which you asked about:

A. Ackuaria. Publisher which video has frozen for one receiver:
![sm_send_freeze](https://user-images.githubusercontent.com/6253301/59332691-7d679400-8cff-11e9-8db2-f3bc2d04eddc.png)

B. Ackuaria. Receiver which has frozen video:
![sm_receive_freeze](https://user-images.githubusercontent.com/6253301/59332723-907a6400-8cff-11e9-90db-8bfd7d07ef80.png)

C. webrtc-internals: Receiver which has frozen video:
![sm_receve_freeze_wrtc_int](https://user-images.githubusercontent.com/6253301/59332784-b6a00400-8cff-11e9-97fb-c1f49931462e.png)

D. Ackuaria. Receiver of the same published but it is OK:
![sm_receive_not_freeze](https://user-images.githubusercontent.com/6253301/59332744-a425ca80-8cff-11e9-8d52-81472109a47a.png)

Thanks!

**Comment by lodoyun** [comment] 2019-06-12 13:15
First of all... The behaviour in your first post is different from this, there you can see the simulcast layers in the subscriber graph -> the stream was in fallback mode, disabled since #1417. This is a different issue, even if the effect is similar.

That does look like the Licode subscription is broken for some reason. Particularly, not seeing the publisher's simulcast layers in the ackuaria graph for a subscriber is something I've not seen before.

I'm trying to reproduce this but I haven't been able to, so let me ask you a few more questions to see if I can get an environment closer to yours. 
**Browser**
- I'm using Chrome 75. Have you tried it?
- Since you mention your computer... Are you running two OSs via virtualization in one computer?
- Have you found any patterns about the OS where the clients are? i.e. the issue happens only in Windows. This is far fetched as it looks like the issue is with Licode itself but it would be interesting to know.
- Is the licode connection for that subscription dropped after a while?
**Licode configuration**
Are you setting a maxVideoBW for the streams? 
Are you using Single peerConnection?
`config.erizoAgent.maxProcesses`?
**Server**
Are you using our docker image?
Any modification to the code base?
Is the server in your own infrastructure or in a public one? 
Is there significant network delay between the clients and the servers?

**Comment by vpoddubchak** [comment] 2019-06-13 11:59
- Just tried with Chrome v75. I would say that is becomes more stable: I had to add more participants to reproduce issue: 2 on Win7, 2 on Ubuntu 14, 2 on Ubuntu 16. and instead of frozen last frame, I saw black picture. (possibly because of your latest commit in master)
 - It is real PC. No virtualization.
 - I can't detect any patterns about OS and other variables... 
 - I do not see dropping connection. And other participants still receiving media from this publisher.
**Licode configuration:**
 - yes, for those tests we use maxVideoBW=512kbps
 - config.erizoController.allowSinglePC = false;
 - config.erizoAgent.maxProcesses=1
**Server**
 - we created own docker image
 - we do not do any modifications in source code base
 - server is public
 - no significant delays

**Comment by lodoyun** [comment] 2019-06-17 10:03
Thanks for all that information, that was useful. I'll try adding more participants just in case.
Also, the last time you reproduced it with Chrome 75, did you check that the publisher was sending video and the problematic subscriber was not receiving any video bits with ackuaria?

**Comment by vpoddubchak** [comment] 2019-06-20 07:04
I retested again:
- Windows 7 Chrome 75 3 tabs
- Ubuntu 14 Chrome 75 3 tabs
So I had 6 participants in room. Simulcast is ON.

First 15 minutes all was great. Then I got first freeze, it was publisher from Ubuntu. After 5 minutes - new freeze, again from Ubuntu.

I checked ackuaria, here is graphics:
1. I found subscriber with no layers on his graph:
![chrome_75_frozen](https://user-images.githubusercontent.com/6253301/59827531-998fb480-9341-11e9-8374-75e03fdd2d5a.png)
2. Then I start searching for another subscriber of the same publisher to check if it is OK for him, and I was lucky to see moment when layers go down. So it is another subscriber of the same publisher:
![chrome_75_just_froze](https://user-images.githubusercontent.com/6253301/59827580-c5129f00-9341-11e9-8d77-fa0c20a93ec4.png)
3. Then I select next subscriber of the same published and see that receiving bitrate is high but no simulcast layers, looks strange:
![bitrate_without_layers](https://user-images.githubusercontent.com/6253301/59827640-e4a9c780-9341-11e9-82d6-8625e76b80ef.png)
4. And there publisher's statistic, all looks good:
![publisher](https://user-images.githubusercontent.com/6253301/59827663-f55a3d80-9341-11e9-9232-ac992cdbd35a.png)

Few details:
1. All frozen videos are published by Ubuntu
2. 15 mins was ok, then I had 2 sec freeze of all Ubuntu system, after that, problems start happening.
3. After 40 min of testing, I have no frozen video from Windows but I have different frozen videos from Ubuntu. 

Hope it helps.

**Comment by vpoddubchak** [comment] 2019-07-02 14:16
I have reproduced it on licode's basic example. Here are steps:

**on PC1:**
1. deployed licode from docker
2. Started example page http://localhost:3001/?simulcast=true
3. Started viewer page: http://localhost:3001/?onlySubscribe=true
4. Started stats tool page: http://localhost:3001/quality_layers.html

**on PC2** (in the same local network):
1. Started viewer page http://<IP_Adress_PC1>:3001/?onlySubscribe=true
2. See nice video from PC1
3. Limit incomming trafic to 80kbps by NetLimiter tool for 15 sec
4. Remove limitation of trafic
5. Video froze forever
6. Receiver stats for frozen viewer:
![image (9)](https://user-images.githubusercontent.com/6253301/60519757-dc13a280-9cec-11e9-9ca8-91639c4d06f1.png)

If start example without simulcast, stream restores correctly on receiving side.

**Comment by lodoyun** [comment] 2019-07-05 08:28
I'm pretty sure that is not the version we have in the repository. We were not updating the `latest` tag properly in the docker repo so, if you are using `latest` you're getting an older version of the code. We are fixing that, in the meantime please run `docker pull lynckia/licode:staging` and use that image.

**Comment by vpoddubchak** [comment] 2019-07-05 13:25
Thanks for update. 
I can't reproduce it with licode:staging image.

**Comment by lodoyun** [comment] 2019-07-08 13:05
👏 I'm going to close this then. Thanks!

**Closed by lodoyun** 2019-07-08 13:05 UTC
